apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  # property-like keys; each key maps to a simple value
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_ORG: kickin
  DOCKER_INFLUXDB_INIT_BUCKET: monitoring
  DOCKER_INFLUXDB_INIT_RETENTION: "1w"
  