apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
  namespace: monitoring
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: influxdb-setup
          image: influxdb:v2.0-alpine
          command:
            - influx
          args:
            - setup
            - --host
            - http://influxdb.monitoring:8086
            - --bucket
            - "$(DOCKER_INFLUXDB_INIT_BUCKET)"
            - --org
            - "${DOCKER_INFLUXDB_INIT_ORG}"
            - --password
            - yogsothoth
            - --username
            - "$(DOCKER_INFLUXDB_INIT_USERNAME)"
            - --retention
            - "$(DOCKER_INFLUXDB_INIT_RETENTION)"
            - --force
          envFrom:
            - configMapRef:
                name: influxdb-config
            - secretRef:
                name: influxdb-admin 