apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: hello-world
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      log.console.level = debug  
      default_user=admin
      default_pass=password